# Generated by Django 2.2.1 on 2019-08-16 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.IntegerField(default=-1, verbose_name='Customer Id')),
                ('CustomerTypeId', models.IntegerField(default=-1, verbose_name='CustomerType Id')),
                ('ProductId', models.IntegerField(default=-1, verbose_name='Product Id')),
                ('FirstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=255, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=255, verbose_name='Last Name')),
                ('GstOrPanNo', models.CharField(max_length=255, verbose_name='GST or PAN Number')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('EmailId', models.CharField(max_length=255, verbose_name='Email Id')),
                ('MobileNo', models.IntegerField(verbose_name='Mobile Number')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ExpiredAt', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Expired At')),
                ('UserId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
