# Generated by Django 2.2.1 on 2019-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='MobileNo',
            field=models.BigIntegerField(verbose_name='Mobile Number'),
        ),
    ]
