# Generated by Django 2.2.1 on 2019-08-16 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CottonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CottonDetailsId', models.IntegerField(default=-1, verbose_name='CottonDetails Id')),
                ('SerialNo', models.CharField(max_length=255, verbose_name='Serial No')),
                ('VehicleNo', models.CharField(max_length=255, verbose_name='Vehicle No')),
                ('BuyDate', models.DateField(verbose_name='Buy Date')),
                ('Village', models.CharField(max_length=255, verbose_name='Village')),
                ('Vyapari', models.CharField(max_length=255, verbose_name='Vyapari')),
                ('BrokerId', models.IntegerField(default=-1, verbose_name='Broker Id')),
                ('GrossWeight', models.IntegerField(verbose_name='Gross Weight')),
                ('EmptyVehicleWeight', models.IntegerField(verbose_name='Empty Vehicle Weight')),
                ('Kanta', models.IntegerField(verbose_name='Kanta')),
                ('Moisture', models.IntegerField(verbose_name='Moisture')),
                ('UtaraSample', models.FloatField(verbose_name='UtaraSample')),
                ('UtaraGeneral', models.FloatField(verbose_name='UtaraGeneral')),
                ('Utara3', models.FloatField(verbose_name='Utara3')),
                ('RatePerKg', models.IntegerField(verbose_name='RatePerKg')),
                ('Vatav', models.IntegerField(verbose_name='Vatav')),
                ('Girai', models.IntegerField(verbose_name='Girai')),
                ('PaymentStatus', models.CharField(default='INITIAL', max_length=255, verbose_name='Payment Status')),
                ('Advance', models.FloatField(verbose_name='Advance')),
                ('TruckTarrif', models.FloatField(verbose_name='Truck Tarrif')),
                ('LumpsumAmountPaid', models.FloatField(verbose_name='Lumpsum Amount Paid')),
                ('PaymentDate', models.DateField(verbose_name='Payment Date')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ExpiredAt', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Expired At')),
                ('UserId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
