# Generated by Django 2.2.1 on 2019-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonDetails', '0002_auto_20190816_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottondetails',
            name='PaymentDate',
            field=models.DateField(auto_now_add=True, verbose_name='Payment Date'),
        ),
    ]
