# Generated by Django 2.2.1 on 2019-11-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonDetails', '0003_auto_20190816_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottondetails',
            name='BalanceAmount',
            field=models.FloatField(default=0.0, verbose_name='Balance Amount to be Paid'),
        ),
    ]
