# Generated by Django 2.2.1 on 2019-11-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CottonDetails', '0004_cottondetails_balanceamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottondetails',
            name='PaymentStatus',
            field=models.CharField(default='Pending', max_length=255, verbose_name='Payment Status'),
        ),
    ]
