# Generated by Django 2.2.1 on 2019-11-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20190816_1417'),
        ('CottonDetails', '0005_auto_20191103_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cottondetails',
            name='BrokerId',
        ),
        migrations.AddField(
            model_name='cottondetails',
            name='Broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer'),
            preserve_default=False,
        ),
    ]
