# Generated by Django 2.2.1 on 2019-08-16 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QualityTypeId', models.IntegerField(default=-1, verbose_name='Quality Type Id')),
                ('Length', models.IntegerField(verbose_name='Length')),
                ('Mic', models.IntegerField(verbose_name='MIC')),
                ('Trash', models.IntegerField(verbose_name='Trash')),
                ('Rd', models.IntegerField(verbose_name='RD')),
                ('Grade', models.CharField(max_length=255, verbose_name='Grade')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ExpiredAt', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Expired At')),
                ('UserId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.IntegerField(default=-1, verbose_name='Product Id')),
                ('ProductName', models.CharField(max_length=255, verbose_name='Product Name')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('ExpiredAt', models.DateTimeField(default=datetime.datetime(3000, 1, 1, 0, 0), verbose_name='Expired At')),
                ('UserId', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
